### ISSUE TITLE
README should include clear intersections on how to run the example

### ISSUE THREAD

**Issue by tzach** [Laurent56/scylla_shopping#1]

**Comment by Laurent56** [comment]
Hi Tzach,
I added instructions to run the code using /src/main/java/com/scylladb/shop/TestFramework.java main() method. I was told by you to stop working on this, so I am not sure how much time you want me to invest in writing the README.md file. I can make a more thorough set of run instructions if what I have written is not clear or not detailed enough. Thanks.
